In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df_raw = pd.read_csv("../stations.csv")

C:\Users\wwsam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\IPython\core\interactiveshell.py:3340: DtypeWarning: Columns (9,18,19,23,34,36,37,46,49,52,55,56,60,61,62,63,64,65) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
df_raw.describe()

,X,Y,OBJECTID,PLUS4,EV_LEVEL1_EVSE_NUM,EV_LEVEL2_EVSE_NUM,EV_DC_FAST_COUNT,LATITUDE,LONGITUDE,ID,...,INTERSECTION_DIRECTIONS_FRENCH,ACCESS_DAYS_TIME_FRENCH,BD_BLENDS_FRENCH,CNG_DISPENSER_NUM,CNG_TOTAL_COMPRESSION_CAPACITY,CNG_STORAGE_CAPACITY,EV_PRICING_FRENCH,RESTRICTED_ACCESS,LATDD,LONGDD
count,59927.000000,59927.000000,59927.000000,0.0,1003.000000,44762.000000,5905.000000,59927.000000,59927.000000,59927.000000,...,0.0,0.0,0.0,987.000000,689.000000,337.000000,0.0,0.0,59927.000000,59927.000000
mean,-97.729076,37.752821,29964.000000,NaN,3.367896,2.312855,3.739881,37.754624,-97.731622,137252.646970,...,NaN,NaN,NaN,2.247214,883.867925,49215.166172,NaN,NaN,37.752821,-97.729076
std,18.997244,5.012616,17299.579128,NaN,7.272652,3.264666,4.324265,5.005829,18.994369,53934.805321,...,NaN,NaN,NaN,3.582932,1012.292526,55211.543179,NaN,NaN,5.012616,18.997244
min,-159.788556,0.000000,1.000000,NaN,1.000000,1.000000,1.000000,18.334138,-159.788556,17.000000,...,NaN,NaN,NaN,0.000000,2.000000,0.000000,NaN,NaN,0.000000,-159.788556
25%,-118.027879,34.029061,14982.500000,NaN,1.000000,2.000000,1.000000,34.029196,-118.027981,95158.500000,...,NaN,NaN,NaN,1.000000,240.000000,30375.000000,NaN,NaN,34.029060,-118.027879
50%,-94.572079,38.076412,29964.000000,NaN,1.000000,2.000000,2.000000,38.076869,-94.572901,159608.000000,...,NaN,NaN,NaN,2.000000,650.000000,36000.000000,NaN,NaN,38.076412,-94.572079
75%,-80.822796,41.381453,44945.500000,NaN,2.000000,2.000000,4.000000,41.381960,-80.823263,180119.500000,...,NaN,NaN,NaN,2.000000,1100.000000,60000.000000,NaN,NaN,41.381453,-80.822796
max,0.000000,64.852466,59927.000000,NaN,90.000000,311.000000,56.000000,64.852466,0.000000,203431.000000,...,NaN,NaN,NaN,52.000000,8250.000000,593136.000000,NaN,NaN,64.852466,0.000000

In [9]:
df_locs = df_raw[["X", "Y"]].copy()

In [12]:
df_locs.to_json("../locs.json", orient="records")